### ISSUE TITLE
select/create category on branch creation

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitverModules#11]
Git provides the organization of branches by using slash (/) separated branch names. We can use that benefitial in two ways:
- Show branches (references in general) in a file-tree like structure
- When creating a branch, the user could select default categories and add his own.

Something like a combobox or list shows the available categories, inside the "create branch" dialog. In addition, predefined categories could be:

```
* <none> (no category, should also be possible)
* topic
* feature
* bug
```

This honours the Vinecent Driessen branch model and gives additional flexibility. Plus, accidental typos are minimized :smile:

**Comment by scunz** [comment]
707545bd should help us addressing this... :smile:

**Comment by antis81** [comment]
Ok. This would be a little, but nice feature.

**Comment by scunz** [comment]
It actually means: The tag / branch selection in already commited History-Diff is working like that. It requires icons and better sorting, though, but that's for later fixing :)

**Comment by antis81** [comment]
Closing in favor to [Redmine](http://redmine.macgitver.info/issues/188)
