### ISSUE TITLE
Commit Workingtree

### ISSUE THREAD

**Issue by scunz** [macgitver/MacGitverModules#31]

**Comment by antis81** [comment]
Do you mean the `stage/index` here? In my oppinion this is one of the main features blocking us from getting the `Genesis` version ready.

**Comment by scunz** [comment]
Hmm, thinking shortly about this: From a functional point of view, i agree that this would be what's mostly keeping a 0.1 release in the shaddows...

However, if we allow to commit the `index` then we should really ask ourselves first: how should the user be able to _add_ something to the index? Or in longer words: Yes, I think that we need to be able make a new commit out of the index. But we first need to implement adding files (or even hunks) to the index.

So, in a first roundtrip, I'd suggest the following:
- Implement a Dialog. It has only to have one `QListWidget`, a `QPlainTextEdit` and a buttonBox.
- The list gets configured to show a single column, each with a checkbox.
- On opening that dialog, we do something along the lines of a `git diff-tree`.
- A diff-tree is fairly simple to do: We can duplicate the `diff_xxx_to_yyy` methods - But instead of using the `PatchConsumer` we would have to use the `ChangeListConsumer`. From therein we just put all the data that is given to the `ChangeListConsumer` into a flat `QList< Change >` With change being a `struct Change{ QString oldFile, newFile; ... };`.
- We put each entry of that list into the listwidget, coloring removals red and additions green and marking all checkboxes.
- We add a Button `commit`. When pressed, we use a `Git::TreeBuilder` to mix the existing index with the selection in the list widget. With the resulting tree, the message in the plain text edit and the signature data from the config-subsystem, we then can create a new commit.

I've been distracted quite a bit (again) recently. I'm not sure as to when I will actually be working on mgv again...

**Comment by antis81** [comment]
Not a problem. I send a PR (well, maybe next week or so :smile:) and we discuss it when it is available.

**Comment by scunz** [comment]
Would be cool.

**Comment by antis81** [comment]
Hi. Thaught the time is right to do it :smile:. So I set up another branch `topic/IndexView` and added a simple stupid dialog there. Found it to be simpler to start off this way, than a PR. Could you review please? It is not much - basically the UI right now. I just like to know, if the QListView for the "Diff" is going in the right direction.

**Comment by scunz** [comment]
Yeah, I think this is going in the right direction. I've thought several times about creating a view to the index, but always dismissed it.

Just two nitpicks:
- You shouldn't put yourself on the shelf. Go on and put your name into the copyright message, where it probably belongs :cake:
- This early stage still contains some references to the Submodule code where it was copied from.

**Comment by antis81** [comment]
Ya got me, I copied the module as a template. Thanks for the hint :+1: - I will fix that. Btw.: The commit dialog UI is made similar to the GitX one (see https://github.com/rowanj/gitx).

**Comment by antis81** [comment]
Got a quick preview implementation of the ´diffIndexToWorkingTree` thingy. Far from really usable, but shows it generally works! Well, kind of :smile:

**Comment by antis81** [comment]
Closing this one as we have implemented it, addressed in [Redmine](http://redmine.macgitver.info/issues/25). The basic commit mechanism with staging/unstaging files and creation a commit with message. There's no linewise staging yet, but we really need to cleanly bring that one into our Roadmap in the project system.
