### ISSUE TITLE
Moving Wiki from MacGitverModules to MacGitver

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitverModules#55]
@scunz I'd like to bring the "old" wiki from MacGitverModules into the MacGitver project main wiki. This needs very little work - only the empty 'Home' page is replaced and by pushing the results back it's done.

**Comment by scunz** [comment]
I thought we already agreed on that, didn`t we?

**Comment by antis81** [comment]
Yes, just wanted to let you know. Thanks for the quick answer. So, I'm gonna do it - well, right now :smile:.

**Comment by scunz** [comment]
However, i think these Actions docs that are contained there should(in a longer term) be moved to doxygen and be contained in the libHeaven repo.

Did you have some looks at my recent commits to all these uncrappify branches?

**Comment by antis81** [comment]
Would be totally cool, if the API docs were available from within the libs. Even cooler would be a page in the fashion of libgit2, documenting the version changes to the API over time - also not perfect, but very good.

For the uncrappify branches, I followed roughly as it is really huge and I'm really excited, finally being able to use it :+1:  :+1:. Could you send some `hid` sample files and maybe some screenhots?

**Comment by scunz** [comment]
I have actually changed no hids. Ypu probably mean thr layout xml. That is already in. I think that i will be able to check on a working version somewhen tonight...

**Comment by antis81** [comment]
Ok. Let's just close this issue as it is done. Feel free to remove the wiki here any time you like.

Rest of discussion concerning the uncrappify branches goes on in the original issue here: https://github.com/macgitver/libHeaven/pull/11

**Comment by scunz** [comment]
I've now disabled all GH-Wikis on the C++ parts of MGV; only the umbrella "MacGitver.git" has a wiki.
