### ISSUE TITLE
Stage/Index view: Merging of WorkingTree + IndexView into one view

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitverModules#58]
Here is the new issue open for discussion. We should also use the PR #57 for realization. Currently it is a separate module called "Index" using a separate view.

EDIT: PR changed to #62.

**Comment by scunz** [comment]
Using #57 for implementation is pretty fine.

The Working-Tree-View currently uses `Git::Repository::statusHash` (which is based on `git_status_foreach_ext`) to create a flat list of files in the working directory. Your suggestion for a Index-View was: get a list of files in the index from `git_status_foreach_ext` and view this in a view. I think that this is a good way to go.

But then we might get a more comfortable user interface, if we:
- extent `Git::Repository::statusHash` to filter its results (i.e. wrap the options given to libgit2 in a `QFlags` from GitWRap).
- Add a set of toggle buttons ('WorkTree only', 'Index only', 'both') [1] to the WorkingTree; only one of them could be activated at a time.
- If **Both** is activated: Build the DiffList as we do it now (WorkTree against Index combined with Index against HEAD); In the files view, show all files that are in the Status-Hash;
- If **Index Only** is activated: Build the DiffList only from Index against HEAD, Show tree only from Index. This implies removal of all "ignored" files.
- If **WT only** is activated: Build the DiffList only from WT against Index. Show tree only for Working Tree. This implies: A file that is not tracked, but has just been added to the index is shown as unmodified.

We should allow the user to add 3 SHA1 columns to the tree: SHA1-Of-HEAD; SHA1-In-Index; SHA1-In-WorkTree

We should setup a table that shows exactly when which state will be shown with what decoration.

[1] After thinking about this, we could also provide a special mode "Conflicts only". But that's a later thing to do...

**Comment by antis81** [comment]
Think we can close this one, can we?

**Comment by scunz** [comment]
Right. This should probably be done totally different with the Mode-Switcher :)
