### ISSUE TITLE
State of the Submodules View

### ISSUE THREAD

**Issue by scunz** [macgitver/MacGitverModules#60]
@antis81,

what shall we do with the view that is included in `ModSubmodules`? 
Do yo think that it will become useful again? In my opinion, we should rather integrate all submodule features into the RepoTree-View provided by `ModRepository`.

**Comment by antis81** [comment]
Yeah, we should really integrate the features in `ModRepository`. Actually it is pretty much the same idea and it is a good thing to drop `ModSubmodules`. If we really want to sneak in :eyes:, I think we are better off by going back in history :bookmark: than letting it linger around there.

**Comment by scunz** [comment]
I don't want to drop `ModSubmodules` _totally_. If that's what you understood, then I might have misspelled my thoughts. What I actually want to do is:
- Remove the _View_ from ModSubmodule. As you already said, it's redundant with the new RepoTree-View.
- I want to keep the submodule-related features in ModSubmodule
- => They should plug into ModRepository via the (next on my ToDo-List) interfaces structure.

**Comment by antis81** [comment]
Ah ok :bulb:. Then I really misunderstood that. Sounds like a good plan :smile:.

**Comment by scunz** [comment]
ModSubmodules is now temporarily disabled.
