### ISSUE TITLE
Better visibility of current branch / commit

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitverModules#7]
It would be nice to see more clearly on which branch we currently work and commit. Maybe the top-bar besides the "History" / "Work Tree" switch would be a better place. Also it could have the "active branch color" (orange). I chose a lighter orange in MsPiggit though as it seems more polite and not shocking the user too much :smile:.

Additionally, the whole line of the current commit (HEAD) could be in the same or similar color to clearly mark it.

**Comment by scunz** [comment]
During the migration from `QStatusBar` to `FooterWidget`, the colors of the status bar were reverted. I think that makes everything, we put into the status bar, more prominent.

**Comment by antis81** [comment]
Think, we can close this one, right?

**Comment by scunz** [comment]
Think so :)
