### ISSUE TITLE
Config Dialog

### ISSUE THREAD

**Issue by scunz** [macgitver/MacGitverModules#84]
Values with dots inside them (which is valid between the first and last dot in the config setting - Woohoo: Only a Torvalds is allowed to create such a concept) are broken down into tree entries, which is obviously wrong.

**Comment by scunz** [comment]
To be more detailed what a simple `git config -l` would list as `branch.foo.bar.remote=origin` is displayed as:

```
branch
    foo
         bar
             remote = origin
```

while it should be:

```
branch
    foo.bar
        remote = origin
```

**Comment by antis81** [comment]
Copied to and referenced in [Redmine](http://redmine.macgitver.info/issues/187).
